site_name: LMU Raumfinder
site_url: http://lmu-navigator.github.io
repo_url: https://github.com/lmu-navigator
pages:
- ['index.md', 'Startseite']
- ['app.md', 'App-Übersicht']
- ['admin.md', 'Admin-Guide']
- ['android.md', 'Android']
- ['ios.md', 'iOS']
- ['server.md', 'Server']
theme: readthedocs
